### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [pret/pokeruby#361]
How do i install in windows like install.md does not help

**Comment by camthesaxman** [comment]
Please tell what happens when you try to set up the repository instead of just saying it doesn't help. The easiest way is probably to go [here](https://sourceforge.net/projects/devkitpro/files/Automated%20Installer/) and download and install devkitProUpdater-1.6.0 and install devkitARM and MSYS. Then open the devkitPro -> MSys entry in your start menu. You can then clone the repository using `git clone https://github.com/pret/pokeruby.git` if you have git installed, or download the zip and extract it. INSTALL.md should be fairly straightforward from that point on.

Hope that helps.

**Comment by TheRealPiggyWiggy** [comment]
how to install git?

**Comment by ProjectRevoTPP** [comment]
Do you use cygwin? You just need to install the `git` package through its installer.

**Comment by TheRealPiggyWiggy** [comment]
no im installing msys

**Comment by camthesaxman** [comment]
I figured you'd already be using git if you're on GitHub and have created a repository, but there is a convenient Windows installer. https://git-scm.com/download/win Make sure you choose the option for git to be in your PATH (not the additional unix utilities, just have git in your PATH) so you will be able to use it from the MSYS shell.

Not all of us use Cygwin.

**Comment by camthesaxman** [comment]
Is it working for you?

**Comment by ProjectRevoTPP** [comment]
Why was this closed?
