### ISSUE TITLE
*** No rule to make target `baserom.gba'

### ISSUE THREAD

**Issue by byteandahalf** [pret/pokeruby#5]
`$make`

`make generated`
`make[1]: Entering directory '/c/Users/user/Desktop/git/pokeruby'`
`make[1]: Nothing to be done for 'generated'.`
`make[1]: Leaving directory '/c/Users/user/Desktop/git/pokeruby'`
`make rom`
`make[1]: Entering directory '/c/Users/user/Desktop/git/pokeruby'`
`make[1]: *** No rule to make target 'baserom.gba', needed by 'asm/crt0.o'.  Stop.`
`make[1]: Leaving directory '/c/Users/user/Desktop/git/pokeruby'`
`make: *** [all] Error 2`

I am on Windows.

**Comment by anmart** [comment]
you need to put pokemon ruby in the directory with the name baserom.gba

**Comment by ProjectRevoTPP** [comment]
I am currently trying to get rid of the baserom.gba dependency pokeruby currently has, however, that make take months, if not at least a year.

You will need baserom.gba with the provided sha1 in the INSTALL.md in the meantime, as pokeruby builds with data from the actual game due to it not being dissassembled.

**Comment by YamaArashi** [comment]
Updated the install instructions in 852e2fd5385467a2d7f3c02d77d322a9b88201e9
